theme: jekyll-theme-slate
title: Dr. Lavin's homepage
description: Making a Jekyll site on Github is a snap!
footer: The site mjlavin80.github.io is published using a Jekyll theme on <a href="https://pages.github.com">GitHub Pages</a>
